### ISSUE TITLE
References?

### ISSUE THREAD

**Issue by ppKrauss** [TaehoonK/dggs_code#18]
Hi, is this DGGS is based on the [Sirdeshmukh's master thesis](https://repository.tudelft.nl/islandora/object/uuid%3A56e06ce9-fbad-4ded-8cd5-978f21f9aa2c)?

PS: I am looking for a DGGS with quadrilateral  cells (equal-area rhombus), to represent cell ID by *base16h* codes, [like here](https://ppkrauss.github.io/Sfc4q/). Other quadrilateral DGG  do not meet the basic requirements, e.g.  [S2 Geometry is not equal-area](https://s2geometry.io/resources/s2cell_statistics.html)... But Sirdeshmukh's grid looks good.

**Comment by TaehoonK** [comment]
@ppKrauss, It's a good question. 
As noted in [README](https://github.com/TaehoonK/dggs_code#reference), the primary method is based on Sirdeshmukh's proposed method. 
But the implemented structure is a little bit different; 
- the original one is maximally occupied 32 bits for each axis; x(32), y(32), z(32). But this project used x(32), y(32), z(**_24_**).
- the maximum (or boundary) value of the coordinates boundary is slightly different. (Maximum (and Minimum) Z value is near 10km~ for making the height (and altitude) length as the same length of the side of the rhombus. 
- lastly, the projection method algorithm is different; (it's based on [geogrid](https://github.com/mocnik-science/geogrid), not [Sirdeshmuk's one](https://github.com/geomatician/DGGSPointCloud))
